---
- name: Include baseline user and group management
  ansible.builtin.include_tasks: users.yml
  tags: [common, users]

- name: Include baseline package management
  ansible.builtin.include_tasks: packages.yml
  tags: [common, packages]

- name: Include SSH policy management
  ansible.builtin.include_tasks: ssh.yml
  when: common_manage_ssh
  tags: [common, ssh]

- name: Include time synchronization configuration
  ansible.builtin.include_tasks: time.yml
  tags: [common, time]

- name: Include sysctl tuning
  ansible.builtin.include_tasks: sysctl.yml
  when: common_manage_sysctl
  tags: [common, sysctl]

- name: Include unattended upgrade configuration
  ansible.builtin.include_tasks: unattended.yml
  when: common_unattended_upgrades_enabled
  tags: [common, unattended]

- name: Include firewall configuration
  ansible.builtin.include_tasks: firewall.yml
  when: common_firewall_enabled
  tags: [common, firewall]
