---
- name: Determine Chrony paths and service for this OS
  ansible.builtin.set_fact:
    _chrony_service: "{{ (ansible_facts.os_family == 'RedHat') | ternary('chronyd', 'chrony') }}"
    _chrony_conf: "{{ (ansible_facts.os_family == 'RedHat') | ternary('/etc/chrony.conf', '/etc/chrony/chrony.conf') }}"

- name: Ensure chrony installed
  ansible.builtin.package:
    name: chrony
    state: present

- name: Render chrony configuration
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ _chrony_conf }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart chrony service

- name: Enable and start chrony
  ansible.builtin.service:
    name: "{{ _chrony_service }}"
    state: started
    enabled: true

- name: Set system timezone
  community.general.timezone:
    name: "{{ common_timezone }}"
