---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ base_apt_cache_timeout }}"
  become: true

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ base_sys_packages }}"
    state: present
  become: true

- name: Ensure system is cleaned up
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
  become: true
