---
- name: Apply Base Configuration
  hosts: all
  become: true
  roles:
    - role: base

- name: Apply Site Configuration
  hosts: all
  become: true
  roles:
    - role: site_config

- name: Apply NetBox Configuration
  hosts: netbox
  become: true
  vars_files:
    - ../inventories/lab/group_vars/netbox.yml
  roles:
    - role: netbox_native
  tags:
    - netbox
