---
# Top-level entrypoint playbook
# Runs common baseline on all hosts, and NetBox role on netbox group

- name: Deploy NetBox stack
  hosts: netbox
  become: true
  vars_files:
    - ../inventories/lab/group_vars/netbox.yml
  roles:
    - netbox_native
