---
# Top-level entrypoint playbook
# Runs bootstrap (optional), common baseline, then NetBox role

- name: Bootstrap hosts for Ansible management
  hosts: bootstrap
  gather_facts: false
  become: true
  serial: 1
  roles:
    - role: bootstrap

- name: Apply common baseline
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: common

- name: Deploy NetBox stack
  hosts: netbox
  become: true
  vars_files:
    - ../inventories/lab/group_vars/netbox.yml
  roles:
    - netbox_native
